#!/bin/sh

gcc -ansi -I./ -c ./src/simulation.c -o ./src/simulation.o
gcc -ansi -I./ -c ./src/fileManager.c -o ./src/fileManager.o
gcc -ansi -I./ -c ./src/customerQueue.c -o ./src/customerQueue.o
gcc -ansi -I./ -c ./src/randGenerator.c -o ./src/randGenerator.o

gcc -ansi -g -lm -o simQ ./src/main.c ./src/simulation.o ./src/fileManager.o ./src/customerQueue.o ./src/randGenerator.o

rm ./src/simulation.o ./src/fileManager.o ./src/customerQueue.o ./src/randGenerator.o
