#!/bin/sh

gcc -ansi -I./ -c simulation.c -o simulation.o
gcc -ansi -I./ -c fileManager.c -o fileManager.o
gcc -ansi -I./ -c customerQueue.c -o customerQueue.o
# gcc -Wall -I./gsl_2.6 -c example.c
# gcc -L/usr/local/lib example.o -lgsl -lgslcblas -lm

gcc -ansi -g -o simQ main.c simulation.o fileManager.o customerQueue.o

rm simulation.o fileManager.o customerQueue.o

# make